/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _OOP23_prof_vs_students;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
